import {
  Utensils,
  UtensilsCrossed,
  Coffee,
  Wine,
  CupSoda,
  IceCreamCone,
  CakeSlice,
  Soup,
  Salad,
  Fish,
  Beef,
  Pizza,
  Sandwich,
  Package,
  Leaf,
  Sprout,
  Wheat,
  Milk,
  Egg,
  Flame,
  GlassWater,
  Martini,
  Beer,
  Croissant,
  Cookie,
  Drumstick,
  ChefHat,
  ShoppingBasket,
  Star,
  type LucideIcon,
} from "@lucide/vue"

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  wine: Wine,
  "cup-soda": CupSoda,
  "ice-cream": IceCreamCone,
  cake: CakeSlice,
  soup: Soup,
  salad: Salad,
  fish: Fish,
  beef: Beef,
  pizza: Pizza,
  sandwich: Sandwich,
  package: Package,
  leaf: Leaf,
  sprout: Sprout,
  wheat: Wheat,
  milk: Milk,
  egg: Egg,
  flame: Flame,
  "glass-water": GlassWater,
  martini: Martini,
  beer: Beer,
  croissant: Croissant,
  cookie: Cookie,
  drumstick: Drumstick,
  "chef-hat": ChefHat,
  basket: ShoppingBasket,
  star: Star,
}

export const ICON_OPTIONS = Object.keys(ICON_REGISTRY)

export function resolveIcon(key: string): LucideIcon {
  return ICON_REGISTRY[key] ?? Utensils
}
